---
sidebar: sidebar 
permalink: concept-licensing-charging.html 
keywords: capacity-based license charging, consumption for licenses, pricing for licenses, CVO licensing, CVO charging, SnapLock charging, CIFS charging, audit volumes, primary volumes, volume-based charging 
summary: 熟悉基于容量的许可证的收费、消费模式、定价和配置。 
---
= 了解有关Cloud Volumes ONTAP基于容量的许可证的更多信息
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 基于容量的许可决定存储容量、套餐和超额的计费方式。使用此信息了解计费和容量消耗，尤其是对于标准模式部署。

私有模式部署只能在 Bring-Your-Own License (BYOL) 模型中使用基于容量的 Essentials 包。有关私有模式部署的许可详细信息，请参阅 link:concept-license-management.html["了解Cloud Volumes ONTAP BYOL"^]。



[[consumption-models-and-purchase-options]]
== 消费模式和购买选项

我们提供基于容量的许可套餐，并有以下几种消费模式或购买选项：

* *Marketplace subscriptions/Annual contract*：来自云提供商市场的年度合同。私有模式部署不支持市场订阅。
* *PAYGO*：即用即付 (PAYGO) 订阅是从云提供商市场按小时订阅的。
* *BYOL*：自带许可证（BYOL）。从 NetApp 购买的许可证，可用于在任何云提供商中部署 Cloud Volumes ONTAP。
+

NOTE: NetApp 已限制 BYOL 许可的购买、扩展和续订，并在特定场景（例如私有模式部署）中限制了其可用性。有关详细信息，请参阅 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Cloud Volumes ONTAP的 BYOL 许可可用性受限"^]。



请注意以下事项：

* 如果您从 NetApp 购买 BYOL 许可证，您还需要在云提供商的市场上订阅 PAYGO 产品。NetApp 已限制标准模式部署的 BYOL 许可。当您的 BYOL 许可证到期时，请将其替换为云市场订阅。
+
您的许可证始终会被首先收费，但在以下情况下，我们将按照市场上的小时费率向您收费：

+
** 如果您超出许可容量
** 如果您的许可证期限已到期


* 如果您拥有 BYOL 许可证和来自市场的年度合同，我们将根据您设置的账单偏好向您收取消费和超额费用。要了解如何收取费用，请参阅link:concept-licensing-charging.html#billing-preferences-and-overages["计费偏好和超额费用"]。
* 中国地区仅支持具有 BYOL 的单节点系统。中国地区的部署不受 BYOL 许可限制。




[[how-you-are-charged-for-supported-storage-types-and-packages]]
== 支持的存储类型和套餐如何收费

Cloud Volumes ONTAP的计费基于多种因素，例如套餐和卷类型。Cloud Volumes ONTAP 9.7 及更高版本提供基于容量的许可包。

以下各节将解释收费内容、适用最低金额的地方以及超额收费方式。

有关定价的详细信息，请转到 https://bluexp.netapp.com/pricing/["NetApp Console网站"^]。



[[storage-vms]]
=== Storage VM

* 额外的数据服务存储虚拟机 (SVM) 没有额外的许可费用，但每个数据服务 SVM 的最低容量收费为 4 TiB。
* 灾难恢复 SVM 根据预置容量收费。




[[ha-pairs]]
=== HA 对

对于 HA 对，您只需为节点上配置的容量付费。您无需为同步镜像到合作伙伴节点的数据付费。



[[flexclone-and-flexcache-volumes]]
=== FlexClone和FlexCache卷

* 您无需为FlexClone卷使用的容量付费。
* 源和目标FlexCache卷被视为主数据，并根据配置的空间收费。




[[readwrite-volumes]]
=== 读/写卷

可写（读/写）卷是主卷。系统根据每个存储虚拟机 (SVM) 的最低费用对配置的容量收费。示例包括 FlexVol 读/写卷、SnapLock 审核卷和 CIFS/NFS 审核卷。所有用户创建的数据卷均根据您的订阅和套餐类型收费。ONTAP 内部卷（如 SVM 根卷）不计费，因为它们是自动创建的，无法存储数据。



[[essentials-packages]]
=== 基本套装

Essentials 包按部署类型（HA 或单节点）和卷类型（主或辅助）计费。定价从高到低依次为：_Essentials Primary HA_、_Essentials Primary Single Node_、_Essentials Secondary HA_ 和 _Essentials Secondary Single Node_。如果您购买市场合同或接受私人优惠，则任何部署或卷类型的容量费用均相同。

许可完全基于Cloud Volumes ONTAP系统内创建的卷类型：

* 基本单节点：仅使用一个ONTAP节点在Cloud Volumes ONTAP系统上创建的读/写卷。
* Essentials HA：使用两个ONTAP节点读取/写入卷，这两个节点可以相互故障转移，以实现无中断数据访问。
* 基本辅助单节点：仅使用一个ONTAP节点在Cloud Volumes ONTAP系统上创建的数据保护 (DP) 类型卷（通常是只读的SnapMirror或SnapVault目标卷）。
+

NOTE: 如果只读 DP 卷成为主卷，Console 会将其视为主数据，并根据卷保持读/写模式的时间计算费用。如果卷再次变为只读，Console 会将其视为辅助数据，并根据 Console 中最匹配的许可证向其收费。

* 基本辅助 HA：在Cloud Volumes ONTAP系统上使用两个可以相互故障转移以实现无中断数据访问的ONTAP节点创建的数据保护 (DP) 类型卷（通常是只读的SnapMirror或SnapVault目标卷）。




[[minimum-charge]]
== 最低收费

对于每个具有至少一个主（读写）卷的提供数据的存储虚拟机，最低收费为 4 TiB。如果主卷的总和小于 4 TiB，则控制台将对该存储虚拟机应用 4 TiB 的最低费用。

如果您尚未配置任何卷，则不适用最低费用。

对于 Essentials 包，4 TiB 最低容量费用不适用于仅包含辅助（数据保护）卷的存储虚拟机。例如，如果您有一个包含 1 TiB 二级数据的存储虚拟机，那么您只需为该 1 TiB 数据付费。对于专业套餐类型，无论卷类型如何，最低容量收费均为 4 TiB。



[[billing-preferences-and-overages]]
== 计费偏好和超额费用

您可以在控制台的“*Licenses and subscriptions*”部分选择您的收费方式。当您的使用量超过许可证套餐或年度订阅中规定的容量时，就会产生超额费用。

* * NetApp优先授权*：在此模式下，您的使用量首先会根据您的许可证包（自带许可证）的容量进行计费。如果您超出许可容量，超出部分将根据您的年度市场订阅或市场按需小时费率（PAYGO）收取费用。如果您的 BYOL 许可证到期，您必须通过云市场过渡到基于容量的许可模式。更多信息请参阅 link:task-convert-node-capacity.html["将Cloud Volumes ONTAP基于节点的许可证转换为基于容量的许可证"]。
* *仅限市场订阅用户*：在此模式下，您的使用费用将首先计入您的年度市场订阅费用。任何额外使用均按市场按需小时费率（PAYGO）收费。任何未使用的许可证容量在计费时均不予考虑。


有关账单偏好设置的更多信息，请参阅 https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["了解许可证和订阅的计费方式"^]。



[[how-overages-are-charged-for-essentials-licenses]]
=== Essentials许可证超额费用如何收取

如果您从NetApp购买 Essentials 许可证（自带许可证），并且超出了特定 Essentials 软件包的许可容量，则控制台会将超出部分的费用计入价格更高的 Essentials 许可证（如果您有可用容量的许可证）。游戏主机首先会使用您已付费的可用容量，然后再向市场收费。如果您的 BYOL 许可证没有可用容量，超出容量的部分将按市场按需小时费率 (PAYGO) 收费，并添加到您的月账单中。

同样，如果您的年度市场合同或包含多个 Essentials 套餐的私人优惠，并且您的使用量超过了特定部署和卷类型的承诺容量，则 Console 将对具有可用容量的价格较高的 Essentials 套餐收取超额费用。在该容量耗尽后，剩余的超额费用将按市场按需（PAYGO）小时费率计费，并添加到您的每月账单中。

要了解有关 Essentials 许可证收费的信息，请参阅 <<基本套装>>。

这是一个例子。假设您拥有 Essentials 包的以下许可证：

* 具有 500 TiB 承诺容量的 500 TiB _Essentials Secondary HA_ 许可证
* 500 TiB _Essentials 单节点_许可证，仅具有 100 TiB 的承诺容量


另外 50 TiB 在具有辅助卷的 HA 对上进行配置。控制台不会向 PAYGO 收取这 50 TiB 的费用，而是向 _Essentials Single Node_ 许可证收取 50 TiB 的超额费用。该许可证的价格高于_Essentials Secondary HA_，但它利用您已购买的许可证，并且不会增加您的每月账单费用。

在“管理”> “Licenses and subscriptions”中，您可以看到针对“Essentials 单节点”许可证收取了 50 TiB 的费用。

这是另一个例子。假设您拥有 Essentials 包的以下许可证：

* 具有 500 TiB 承诺容量的 500 TiB _Essentials Secondary HA_ 许可证
* 500 TiB _Essentials 单节点_许可证，仅具有 100 TiB 的承诺容量


另外 100 TiB 在具有主卷的 HA 对上进行配置。您购买的许可证没有_Essentials Primary HA_承诺容量。  _Essentials Primary HA_ 许可证的价格高于 _Essentials Primary Single Node_ 和 _Essentials Secondary HA_ 许可证。

在此示例中，控制台按照市场价格对额外的 100 TiB 收取超额费用。超额费用将出现在您的每月账单上。



[[change-license-packages]]
== 更改许可证包

部署后，您可以更改使用基于容量的许可的 Cloud Volumes ONTAP 系统的软件包。例如，如果您使用 Essentials 软件包部署了 Cloud Volumes ONTAP 系统，则可以在业务需求发生变化时将其更改为 Professional 软件包。link:task-manage-capacity-licenses.html["了解如何更改充电方式"]。

NetApp 正在逐步淘汰基于节点的许可，转而支持基于容量的许可。基于节点的许可证在一些较旧的系统中仍然可用，例如 USPS 客户和中国的部署。如果您有基于节点的许可，则可以将其转换为基于容量的许可。有关将基于节点的许可转换为基于容量的许可的信息，请参阅 link:task-convert-node-capacity.html["将基于节点的许可证转换为基于容量的许可证"]。



[[capacity-limit]]
== 容量限制

在基于容量的许可模型中，每个Cloud Volumes ONTAP系统都支持分层到对象存储，并且总分层容量可以扩展到云提供商的存储桶限制。虽然许可证没有施加容量限制，但遵循 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool最佳实践"^]确保在配置和管理分层时实现最佳性能、可靠性和成本效率。

有关每个云提供商的容量限制的信息，请参阅其文档：

* https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["AWS 文档"^]
* https://learn.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account["托管磁盘的 Azure 文档"^]和 https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets["Azure Blob 存储文档"^]
* https://cloud.google.com/storage/docs/buckets["Google Cloud 文档"^]




[[max-number-of-systems]]
== 最大系统数量

基于容量的许可将每个 NetApp Console 组织限制为 24 个 Cloud Volumes ONTAP 系统。_system_ 可以是 Cloud Volumes ONTAP HA 对、Cloud Volumes ONTAP 单节点系统或您创建的其他 Storage VM。默认 Storage VM 不计入限制。此限制适用于所有许可模式。

例如，假设您有三个系统：

* 具有一个存储虚拟机的单节点Cloud Volumes ONTAP系统（这是部署Cloud Volumes ONTAP时创建的默认存储虚拟机）
+
该系统算作一个系统。

* 具有两个存储虚拟机（默认存储虚拟机，加上您创建的一个额外的存储虚拟机）的单节点Cloud Volumes ONTAP系统
+
此系统计为两个系统：一个用于单节点系统，一个用于附加存储 VM。

* 具有三个存储虚拟机（默认存储虚拟机，以及您创建的两个额外的存储虚拟机）的Cloud Volumes ONTAP HA 对
+
该系统计为三个系统：一个用于 HA 对，两个用于附加存储虚拟机。



总共有六个系统。这样一来，您的组织中就可以再容纳 14 个系统。

如果您的大型部署需要超过 24 个系统，请联系您的客户代表或销售团队。

了解以下项的存储空间限制：

* AWS：link:reference-limits-aws.html["AWS 中Cloud Volumes ONTAP的存储限制"]
* Azure： link:reference-limits-azure.html["Azure 中Cloud Volumes ONTAP的存储限制"]
* Google Cloud：link:reference-limits-gcp.html["Google Cloud 中 Cloud Volumes ONTAP 的存储限制"]


.相关链接
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP许可"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-capacity-licenses.html["管理Cloud Volumes ONTAP基于容量的许可"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-node-licenses.html["管理基于节点的许可"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-convert-node-capacity.html["将基于节点的许可证转换为基于容量的许可证"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-keystone.html["管理Keystone订阅"^]

