---
sidebar: sidebar 
permalink: concept-configuration-analysis-cvo.html 
keywords: Cloud Volumes ONTAP, configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations 
summary: 从 NetApp Console，Workload Factory 会定期分析存储系统配置，以确定您的 Cloud Volumes ONTAP 系统是否存在任何配置问题。 
---
= Azure 中 Cloud Volumes ONTAP 系统的配置分析
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory 定期从 NetApp Console 分析存储系统配置，以确定 Azure 中的 Cloud Volumes ONTAP 系统是否存在任何配置问题。当发现问题时，架构完善的仪表板会显示问题所在以及需要更改的建议，以确保您的存储系统实现最佳性能、成本效益并符合最佳实践。

主要功能包括：

* 每日配置分析
* 针对 NetApp ONTAP 存储系统和合作伙伴存储提供商的自动最佳实践验证
* 主动可观察性
* 从见解到行动


link:https://docs.netapp.com/us-en/workload-family/index.html["详细了解 Workload Factory。"^]



[[how-it-works]]
== 工作原理

Workload Factory 每天分析在支持的云存储系统部署上运行的工作负载。该分析提供架构完善的状态、见解和建议。

每日分析完成后，配置在部署的 Well-architected 仪表板中显示为"已优化"或"未优化"。您将按类别找到配置问题以及配置问题和建议列表。您可以查看配置问题的建议。Workload Factory 可以自动修复某些问题；其他问题需要手动干预。在此情况下，Workload Factory 会提供详细说明，以帮助您实施建议的更改。

您可以忽略不适用于您环境的配置分析。这样可以避免不必要的警报和不准确的优化结果。

您还可以用简单的语言创建自定义规则，以根据组织的标准和 NetApp 最佳实践验证您的环境。通过试运行测试规则，然后安排它们在您的环境中运行。



[[why-it-matters]]
== 为什么很重要

NetApp Workload Factory 通过将持续评估与建议见解和补救措施相结合，将最佳实践应用于大型存储、数据库和 VMware 环境。自动化修复可减少人为错误，确保统一管理，并保持整个工作负载基础架构的性能和可靠性。



[[analysis-requirements]]
== 分析要求

确保与 Cloud Volumes ONTAP 关联的 Console 代理能够访问以下端点：

* \https://api.workloads.netapp.com
* \https://ws.workloads.bluexp.netapp.com




[[best-practices-and-recommendations-for-cloud-volumes-ontap-systems]]
== Cloud Volumes ONTAP 系统的最佳实践和建议

Workload Factory 评估存储配置，以提供 ONTAP 配置最佳实践的深入视图，并确保符合 Azure Well-Architected Framework。评估还提出了改进和修复建议。

架构完善的分析将配置归类为框架的以下支柱：_reliability_、_security_、_operational excellence_、_cost optimization_ 和 _performance efficiency_。



[[reliability]]
=== 可靠性

可靠性可确保工作负载正确一致地执行其预期功能，即使在中断期间也是如此。

* *Snapshot 策略*
+
安排本地快照以实现高效备份和快速恢复。快照是卷的即时时间点映像。

* *SSD 容量余量*
+
将 SSD 存储层利用率保持在 80% 以下，以防止潜在的应用程序读/写和吞吐量影响。您可以手动或自动增加容量。

* *远程数据复制*
+
通过远程复制保护您的 Cloud Volumes ONTAP 数据。远程数据复制通过在不同位置维护数据的同步副本来提供灾难恢复功能，从而在系统故障或灾难发生时确保业务连续性。





[[security]]
=== 安全性

安全强调通过风险评估和缓解策略保护数据、系统和资产。

* *基于 AI 的自主勒索软件防护 (ARP/AI)*
+
NetApp Autonomous Ransomware Protection with AI (ARP/AI) 有助于增强网络弹性，并保护您的卷免受勒索软件威胁。我们建议为所有卷启用 ARP/AI。





[[operational-excellence]]
=== 卓越运营

卓越运营的重点是提供最佳架构和业务价值。

* *卷容量余量*
+
将卷利用率保持在 80% 以下，以防止潜在的应用程序读/写和吞吐量影响。您可以手动增加容量或使用卷自动增长。

* *FlexCache 写入模式*
+
为了获得最佳性能，请选择最适合您的工作负载的 FlexCache 写入模式。写入绕行模式为具有小文件的读取密集型工作负载提供更好的性能，而写回模式为具有大文件的写入密集型工作负载提供更好的性能。

* *FlexCache 副本大小*
+
在缓存卷上启用卷自动调整大小和清理，以保持最佳大小，并将缓存集中在频繁访问（热）数据上，以实现最高效率。

* *ONTAP 版本合规性*
+
升级到最新的 ONTAP 版本，以实现完全兼容性、获得支持并访问新功能。





[[cost-optimization]]
=== 成本优化

成本优化可帮助您在保持低成本的同时为业务创造最大价值。

* *过度配置的 SSD 容量*
+
多余的SSD容量会增加不必要的成本。减少SSD层，同时保持20%的可用空间缓冲区。此操作可能需要数小时到数天，在此期间不支持其他文件系统操作。

* *冷数据分层*
+
启用冷数据分层，将冷数据从 SSD 存储层移动到成本较低的存储。将分层策略应用于每个卷。



.下一步
link:task-improve-configurations-cvo.html["使用 Workload Factory 改进 Azure 中的 Cloud Volumes ONTAP 配置"]
