---
sidebar: sidebar 
permalink: concept-storage-management.html 
keywords: provisioning, capacity management, storage provisioning, manual, automatic, advanced allocation, aggregates, thin provisioning, free space, mode, BlueXP, NetApp Consolecloud manager 
summary: 该控制台提供了Cloud Volumes ONTAP存储的简化和高级管理。 
---
= Cloud Volumes ONTAP存储管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console提供了对Cloud Volumes ONTAP存储的简化和高级管理。


CAUTION: 您必须直接从控制台创建和删除所有磁盘和聚合。您不应从其他管理工具执行这些操作。这样做会影响系统稳定性，妨碍将来添加磁盘的能力，并可能产生冗余的云提供商费用。



== 存储配置

控制台通过为您购买磁盘和管理聚合，使Cloud Volumes ONTAP 的存储配置变得简单。您只需要创建卷。如果您愿意，您可以使用高级分配选项自行配置聚合。



=== 简化配置

聚合为卷提供云存储。当您启动实例以及配置其他卷时，控制台会为您创建聚合。

创建卷时，控制台会执行以下三件事之一：

* 它将卷放置在具有足够可用空间的现有聚合上。
* 它通过为聚合购买更多磁盘将卷放置在现有聚合上。


ifdef::aws[]

+ 如果 AWS 中的聚合支持弹性卷，它还会增加 RAID 组中磁盘的大小。link:concept-aws-elastic-volumes.html["了解有关弹性卷支持的更多信息"] 。

endif::aws[]

* 它为新聚合购买磁盘并将卷放置在该聚合上。


控制台通过查看几个因素来确定新卷的放置位置：聚合的最大大小、是否启用精简配置以及聚合的可用空间阈值。

ifdef::aws[]



==== AWS 中聚合的磁盘大小选择

当控制台在 AWS 中为Cloud Volumes ONTAP创建新聚合时，它会随着聚合数量的增加逐渐增加磁盘大小，以在达到 AWS 数据磁盘限制之前最大化系统容量。

例如，控制台可能会选择以下磁盘大小：

[cols="3*"]
|===
| 总数 | 磁盘大小 | 最大总容量 


| 1 | 500 GiB | 3 TiB 


| 4 | 1 TiB | 6 TiB 


| 6 | 2 TiB | 12 TiB 
|===

NOTE: 此行为不适用于支持 Amazon EBS 弹性卷功能的聚合。启用了弹性卷的聚合由一个或两个 RAID 组组成。每个 RAID 组有四个相同的磁盘，容量相同。link:concept-aws-elastic-volumes.html["了解有关弹性卷支持的更多信息"] 。

您可以使用高级分配选项自行选择磁盘大小。

endif::aws[]



=== 高级分配

您还可以管理聚合。link:task-create-aggregates.html["从“高级分配”页面"] ，您可以创建包含特定数量磁盘的新聚合、将磁盘添加到现有聚合以及在特定聚合中创建卷。



== 容量管理

组织或帐户管理员可以配置控制台来通知您存储容量决策或是否自动为您管理容量需求。

此行为由控制台代理上的_容量管理模式_决定。容量管理模式会影响该控制台代理管理的所有Cloud Volumes ONTAP系统。如果您有另一个控制台代理，则可以进行不同的配置。



=== 自动容量管理

容量管理模式默认设置为自动。在此模式下，控制台每 15 分钟检查一次可用空间比率，以确定可用空间比率是否低于指定的阈值。如果需要更多容量，它会启动购买新磁盘、删除未使用的磁盘集合（聚合）、根据需要在聚合之间移动卷，并尝试防止磁盘故障。

以下示例说明了此模式的工作原理：

* 如果聚合达到容量阈值并且有空间容纳更多磁盘，则控制台会自动为该聚合购买新磁盘，以便卷可以继续增长。
+
ifdef::aws[]



对于支持弹性卷的 AWS 中的聚合，它还会增加 RAID 组中磁盘的大小。link:concept-aws-elastic-volumes.html["了解有关弹性卷支持的更多信息"] 。

endif::aws[]

+ * 如果聚合达到容量阈值并且无法支持任何额外的磁盘，则控制台会自动将卷从该聚合移动到具有可用容量的聚合或新的聚合。

+ 如果控制台为卷创建新的聚合，它会选择适合该卷大小的磁盘大小。

+ 请注意，原始聚合上现在有可用空间。现有卷或新卷可以使用该空间。在这种情况下，空间无法返回给云提供商。

* 如果聚合中超过 12 小时没有卷，控制台就会将其删除。




==== 使用自动容量管理来管理 LUN

控制台的自动容量管理不适用于 LUN。当它创建 LUN 时，它会禁用自动增长功能。



=== 手动容量管理

如果组织或帐户管理员将*容量管理模式*设置为手动，控制台会通知您采取适当的容量决策措施。自动模式中描述的相同示例也适用于手动模式，但是否接受操作取决于您。



=== 了解更多

link:task-manage-capacity-settings.html["了解如何修改容量管理模式"] 。
