---
sidebar: sidebar 
permalink: configuration-analysis-cvo.html 
keywords: Cloud Volumes ONTAP, license, well-architected, WAD, CVO 
summary: NetApp Console 中的架构完善仪表板会定期分析存储系统配置，以确定您的 Cloud Volumes ONTAP 系统是否存在任何配置问题。发现问题时，仪表板会向您显示问题所在，并解释需要更改的内容，以确保您的存储系统实现最佳性能、成本效益和最佳实践合规性。 
---
= Cloud Volumes ONTAP 的配置分析
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: https://docs.netapp.com/us-en/console-well-architected/media/


[role="lead"]
NetApp Console 中的架构完善仪表板会定期分析存储系统配置，以确定您的 Cloud Volumes ONTAP 系统是否存在任何配置问题。发现问题时，仪表板会向您显示问题所在，并解释需要更改的内容，以确保您的存储系统实现最佳性能、成本效益和最佳实践合规性。

主要功能包括：

* 每日配置分析
* 针对 NetApp ONTAP 存储系统和合作伙伴存储提供商的自动最佳实践验证
* 主动可观察性
* 从见解到行动


未解析的指令，位于 https://raw.githubusercontent.com/NetAppDocs/console-well-architected/main/cvo/configuration-analysis-cvo.adoc[] - include::well-architected-workloads.adoc[]



[[analysis-requirements]]
== 分析要求

要进行完整的 Cloud Volumes ONTAP 系统分析，您必须 link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy["部署 NetApp Console agent"^] 在系统与 NetApp Console 之间建立连接。



[[best-practices-and-recommendations-for-cloud-volumes-ontap-systems]]
== Cloud Volumes ONTAP 系统的最佳实践和建议

架构良好的仪表板评估存储配置，以提供 ONTAP 配置最佳实践的深入视图，并符合 Azure Well-Architected Framework。该评估还提出了改进和修复建议。

架构完善的分析将配置归类为框架的以下支柱：_reliability_、_security_、_operational excellence_、_cost optimization_ 和 _performance efficiency_。



[[reliability]]
=== 可靠性

可靠性可确保工作负载正确一致地执行其预期功能，即使在中断期间也是如此。

* *Snapshot 策略*
+
安排本地快照以实现高效备份和快速恢复。快照是卷的即时时间点映像。

* *SSD 容量余量*
+
SSD 存储层容量不应超过 80% 的利用率。这可能会影响对容量池存储层的数据读取和写入，并影响系统的吞吐量。当容量耗尽时，数据卷将变为只读。尝试写入新数据的服务也会失败。





[[security]]
=== 安全性

安全强调通过风险评估和缓解策略保护数据、系统和资产。

* *基于 AI 的自主勒索软件防护 (ARP/AI)*
+
NetApp Autonomous Ransomware Protection with AI (ARP/AI) 有助于增强网络弹性，并保护您的卷免受勒索软件威胁。我们建议为所有卷启用 ARP/AI。





[[operational-excellence]]
=== 卓越运营

卓越运营的重点是提供最佳架构和业务价值。

* *卷容量余量*
+
我们建议卷容量不超过 80% 的利用率。这可能会影响对应用程序的数据读取和写入。卷容量可以手动增加，也可以使用卷自动增长功能自动增加。

* *FlexCache 写入模式*
+
为了获得最佳性能，我们建议使用最适合您的工作负载的 FlexCache 写入模式。写入绕行模式为具有小文件的读取密集型工作负载提供更好的性能，而写回模式为具有大文件的写入密集型工作负载提供更好的性能。

* *FlexCache 副本大小*
+
我们建议在缓存卷上启用卷自动调整大小和清理，以保持最佳大小，并将缓存集中在频繁访问（热）数据上，以实现最高效率。

* *ONTAP 版本合规性*
+
升级到最新的 ONTAP 版本，以实现完全兼容性、获得支持并访问新功能。





[[cost-optimization]]
=== 成本优化

成本优化可帮助您在保持低成本的同时为业务创造最大价值。

* *过度配置的 SSD 容量*
+
过度配置的 SSD 容量层会增加不必要的成本。我们建议在保持 20% 可用空间缓冲区的同时减少 SSD 层容量。减少操作需要数小时到数天，在此期间不支持其他文件系统操作。

* *冷数据分层*
+
启用冷数据分层，将冷数据从 SSD 存储层移动到成本较低的存储。我们建议对每个卷应用分层策略。Azure Blob Storage 用作非活动数据的容量层。



.下一步
link:https://docs.netapp.com/us-en/console-well-architected/cvo/improve-configurations-cvo.html["实施架构良好的 Cloud Volumes ONTAP 系统配置"]

.相关链接
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html#well-architected-configuration-analysis-for-cloud-volumes-ontap-in-azure["Azure 中 Cloud Volumes ONTAP 的良好架构配置分析"^]

