---
sidebar: sidebar 
permalink: task-verify-autosupport.html 
keywords: autosupport, set up autosupport, test autosupport, asup, test asup 
summary: AutoSupport主动监控系统的健康状况并向NetApp技术支持发送消息。默认情况下，每个节点上都启用AutoSupport ，以使用 HTTPS 传输协议向技术支持发送消息。最好验证AutoSupport是否可以发送这些消息。 
---
= 验证Cloud Volumes ONTAP 的AutoSupport设置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AutoSupport主动监控系统的健康状况并向NetApp技术支持发送消息。默认情况下，每个节点上都启用AutoSupport ，以使用 HTTPS 传输协议向技术支持发送消息。最好验证AutoSupport是否可以发送这些消息。

唯一需要的配置步骤是确保Cloud Volumes ONTAP具有出站互联网连接。有关详细信息，请参阅您的云提供商的网络要求。



== AutoSupport要求

Cloud Volumes ONTAP节点需要NetApp AutoSupport的出站互联网访问权限，它可以主动监控系统的健康状况并向NetApp技术支持发送消息。

路由和防火墙策略必须允许 HTTPS 流量到达以下端点，以便Cloud Volumes ONTAP可以发送AutoSupport消息：

* \ https://mysupport.netapp.com/aods/asupmessage
* \ https://mysupport.netapp.com/asupprod/post/1.0/postAsup


如果没有可用的出站互联网连接来发送AutoSupport消息， NetApp Console会自动配置您的Cloud Volumes ONTAP系统以使用控制台代理作为代理服务器。唯一的要求是确保控制台代理的安全组允许通过端口 3128 进行入站连接。部署控制台代理后，您需要打开此端口。

如果您为Cloud Volumes ONTAP定义了严格的出站规则，那么您还需要确保Cloud Volumes ONTAP安全组允许通过端口 3128 进行出站连接。


TIP: 如果您使用 HA 对，则 HA 中介不需要出站互联网访问。

验证出站互联网访问可用后，您可以测试AutoSupport以确保它可以发送消息。有关说明，请参阅 https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html["ONTAP文档：设置AutoSupport"^]。



== 排除AutoSupport配置故障

如果出站连接不可用，并且控制台无法配置您的Cloud Volumes ONTAP系统以使用控制台代理作为代理服务器，您将收到来自控制台的通知，提示您的系统无法发送AutoSupport消息。请按照以下步骤解决此问题。

.步骤
. 使用 SSH 安全地连接到Cloud Volumes ONTAP系统，以使用ONTAP CLI。
+
link:task-connecting-to-otc.html["了解如何通过 SSH 连接到Cloud Volumes ONTAP"] 。

. 查看AutoSupport子系统的详细状态：
+
`autosupport check show-details`

+
回复内容如下：

+
[listing]
----
    Category: smtp
          Component: mail-server
             Status: failed
             Detail: SMTP connectivity check failed for destination:
                     mailhost. Error: Could not resolve host - 'mailhost'
            Corrective Action: Check the hostname of the SMTP server

    Category: http-https
        Component: http-put-destination
            Status: ok
            Detail: Successfully connected to:
                    <https://support.netapp.com/put/AsupPut/>.

          Component: http-post-destination
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/asupprod/post/1.0/postAsup.

    Category: on-demand
          Component: ondemand-server
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/aods/asupmessage.

    Category: configuration
            Component: configuration
                Status: ok
                Detail: No configuration issues found.
    5 entries were displayed.
----
+
如果 http-https 类别的状态是 `OK` 这意味着AutoSupport已正确配置，可以发送消息。

. 否则，请验证每个Cloud Volumes ONTAP节点的代理 URL：
+
`autosupport show -fields proxy-url`

. 如果代理 URL 参数为空，请配置Cloud Volumes ONTAP以使用控制台代理作为代理：
+
`autosupport modify -proxy-url \http://<console agent private ip>:3128`

. 再次确认AutoSupport状态：
+
`autosupport check show-details`

. 如果状态仍然为失败，请验证Cloud Volumes ONTAP和控制台代理之间是否通过端口建立连接。 `3128`。
. 如果验证后状态仍然失败，请通过 SSH 连接到控制台代理。
+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#connect-to-the-linux-vm["了解有关控制台代理连接到 Linux VM 的更多信息"^]

. 前往 `/opt/application/netapp/cloudmanager/docker_occm/data/`。
. 打开代理配置文件 `squid.conf`。这是文件的结构：
+
[listing]
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        http_access allow netapp_support
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on
----
. 如果您的文件中没有Cloud Volumes ONTAP系统的 CIDR 块条目，请添加新条目并允许访问：
+
`acl cvonet src <cidr>`

+
`http_access allow cvonet`

+
以下是一个例子：

+
[listing]
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        acl cvonet src <cidr>
        http_access allow netapp_support
        http_access allow cvonet
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on

----
. 编辑配置文件后，重启代理容器。 `sudo`。然后，根据您使用的是 Docker 还是 Podman，运行以下命令：
+
对于 Docker，请运行 `docker restart squid`。

+
如果您使用的是 Podman，请运行 `podman restart squid`。

. 返回ONTAP CLI 并验证Cloud Volumes ONTAP是否可以发送AutoSupport消息：
+
`autosupport check show-details`



.相关链接
* link:reference-networking-aws.html["AWS 中Cloud Volumes ONTAP的网络要求"^]
* link:reference-networking-azure.html["Azure 中Cloud Volumes ONTAP的网络要求"^]
* link:reference-networking-gcp.html["Google Cloud 中Cloud Volumes ONTAP的网络要求"^]

