---
sidebar: sidebar 
permalink: task-azure-high-availability-mode.html 
keywords: high availability mode, EnableHighAvailabilityMode, action required, nfsv4 
summary: 应启用 Microsoft Azure 的高可用性模式，以减少计划外故障转移时间，并为Cloud Volumes ONTAP启用 NFSv4 支持。 
---
= 在 Azure 中为Cloud Volumes ONTAP启用高可用性模式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
应启用 Microsoft Azure 的高可用性 (HA) 模式，以减少计划外故障转移时间并为Cloud Volumes ONTAP启用 NFSv4 支持。在此模式下，您的Cloud Volumes ONTAP HA 节点可以在 CIFS 和 NFSv4 客户端上的计划外故障转移期间实现较低（60 秒）的恢复时间目标 (RTO)。

从Cloud Volumes ONTAP 9.10.1 开始，我们减少了在 Microsoft Azure 中运行的Cloud Volumes ONTAP HA 对的计划外故障转移时间，并增加了对 NFSv4 的支持。要使这些增强功能可用于Cloud Volumes ONTAP，您需要在 Azure 订阅上启用高可用性功能。

当需要在 Azure 订阅上启用该功能时， NetApp Console会提示您提供这些详细信息。

请注意以下事项：

* 您的Cloud Volumes ONTAP HA 对的高可用性没有问题。此 Azure 功能与ONTAP协同工作，以减少客户端观察到的因计划外故障转移事件导致的 NFS 协议应用程序中断时间。
* 启用此功能不会对Cloud Volumes ONTAP HA 对造成破坏。
* 在您的 Azure 订阅上启用此功能不会给其他虚拟机带来问题。
* Cloud Volumes ONTAP在 CIFS 和 NFS 客户端上的集群和 SVM 管理 LIF 故障转移期间使用内部 Azure 负载均衡器。
* 启用 HA 模式后，控制台每 12 小时扫描一次系统以更新内部 Azure 负载均衡器规则。


具有“所有者”权限的 Azure 用户可以从 Azure CLI 启用该功能。

.步骤
. https://docs.microsoft.com/en-us/azure/cloud-shell/quickstart["从 Azure 门户访问 Azure Cloud Shell"^]
. 注册高可用性模式功能：
+
[source, azurecli]
----
az account set -s AZURE_SUBSCRIPTION_NAME_OR_ID
az feature register --name EnableHighAvailabilityMode --namespace Microsoft.Network
az provider register -n Microsoft.Network
----
. （可选）验证该功能现在是否已注册：
+
[source, azurecli]
----
az feature show --name EnableHighAvailabilityMode --namespace Microsoft.Network
----
+
Azure CLI 应返回类似于以下内容的结果：

+
[listing]
----
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Features/providers/Microsoft.Network/features/EnableHighAvailabilityMode",
  "name": "Microsoft.Network/EnableHighAvailabilityMode",
  "properties": {
    "state": "Registered"
  },
  "type": "Microsoft.Features/providers/features"
}
----

