---
sidebar: sidebar 
permalink: task-convert-node-capacity.html 
keywords: license conversion, convert node-based to capacity based, by-node to by-capacity, license conversion for node based, BlueXP, Console 
summary: '在基于节点的许可证的可用性终止 (EOA) 之后，您应该使用许可证转换工具过渡到基于容量的许可证。' 
---
= 将Cloud Volumes ONTAP基于节点的许可证转换为基于容量的许可证
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在基于节点的许可证的可用性终止 (EOA) 之后，您应该使用NetApp Console中的许可证转换工具过渡到基于容量的许可证。

对于年度或长期承诺， NetApp建议您在 EOA 日期（2024 年 11 月 11 日）或许可证到期日之前联系您的NetApp代表，以确保过渡的先决条件到位。如果您没有Cloud Volumes ONTAP节点的长期合同，并且根据按需付费 (PAYGO) 订阅运行您的系统，那么在 2024 年 12 月 31 日支持终止 (EOS) 之前规划您的转换非常重要。在这两种情况下，您都应确保您的系统满足要求，然后再使用NetApp Console中的许可证转换工具实现无缝过渡。

有关 EOA 和 EOS 的信息，请参阅link:concept-licensing.html#end-of-availability-of-node-based-licenses["基于节点的许可证的可用性终止"]。

NetApp 已限制 BYOL 许可的购买、延期和续期。有关详细信息，请参阅 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Cloud Volumes ONTAP的 BYOL 许可可用性受限"^]。



[[conversion-in-a-standard-mode-deployment]]
== 标准模式部署中的转换

如果您有标准模式部署，则可以使用 NetApp Console 中的许可证转换工具将基于节点的许可证转换为基于容量的许可证。所有云提供商、AWS、Azure 和 Google Cloud 都支持此转换。您可以将基于节点的许可证转换为通过市场购买的任何基于容量的许可证。例如，如果您拥有 PAYGO 标准节点的许可证，则可以将其转换为通过市场购买的任何基于容量的许可证。

.关于此任务
* 当您使用许可证转换工具时，从基于节点到基于容量的许可模型的转换是在现场在线进行的，从而无需进行任何数据迁移或配置额外的云资源。
* 这是一项无中断操作：
+
** 不会发生服务中断或应用程序停机。
** Cloud Volumes ONTAP系统中的帐户和应用程序数据保持不变。
** 转换后，底层云资源不受影响。


* 许可证转换工具支持所有部署类型，例如单节点、单可用区 (AZ) 中的高可用性 (HA)、多 AZ 中的 HA、自带许可证 (BYOL) 和 PAYGO。
* 对于标准模式，该工具支持所有基于节点的许可证作为源，所有基于容量的许可证作为目标。例如，如果您有基于节点的 BYOL 许可证，则可以将其转换为从 NetApp 购买的任何基于容量的许可证。
* 转换后，基于节点的许可证的序列号将替换为基于容量的格式。这是转换过程中的一部分，并将反映在您的 NetApp 支持站点 (NSS) 帐户上。
* 当您过渡到基于容量的模型时，您的数据将继续保留在与基于节点的许可相同的位置。这种方法保证了数据放置不会中断，并在整个过渡过程中坚持数据主权原则。


.开始之前
* 您应该拥有一个具有客户访问权限或管理员访问权限的 NSS 帐户。
+
** 您的 NSS 帐户应使用您用于访问控制台的用户凭据进行注册。
** Cloud Volumes ONTAP系统应链接到具有客户访问权限或管理员访问权限的 NSS 帐户。


* 您应该拥有有效的基于容量的许可证，可以是 BYOL 许可证或市场订阅。
* 您的帐户中应该有基于容量的许可证。此许可证可以是市场订阅，也可以是控制台中 *Licenses and subscriptions* 下提供的 BYOL/私人优惠包。
* 在选择目的地套餐之前，请了解以下标准：
+
** 如果账户具有基于容量的 BYOL 许可证，则所选目标包应与账户的 BYOL 基于容量的许可证保持一致：
+
*** 什么时候 `Professional`被选为目标包，该帐户应具有带有专业包的 BYOL 许可证：
*** 什么时候 `Essentials`被选为目标包，该帐户应具有 Essentials 包的 BYOL 许可证。


** 如果目标包与帐户的 BYOL 许可证可用性不一致，则意味着基于容量的许可证可能不包含所选包。在这种情况下，我们将通过您的市场订阅向您收费。
** 如果没有基于容量的 BYOL 许可证而只有市场订阅，则应确保所选包包含在基于容量的市场订阅中。
** 如果您现有的基于容量的许可证中没有足够的容量，并且您有市场订阅来对额外的容量使用收费，那么您将通过市场订阅为额外的容量付费。
** 如果您现有的基于容量的许可证中没有足够的容量，并且您没有市场订阅来收取额外容量使用的费用，则无法进行转换。您应该添加市场订阅来收取额外容量或将可用容量扩展到当前许可证。
** 如果目标包与帐户的 BYOL 许可证可用性不一致，并且您现有的基于容量的许可证中没有足够的容量，那么您将通过市场订阅付费。





NOTE: 如果任何一项要求未得到满足，则许可证转换不会发生。在特定情况下，许可证可能会转换，但不能使用。单击信息图标来识别问题并采取纠正措施。

.步骤
. 从左侧导航菜单中，选择“存储”>“管理”。
. 在“*系统*”页面上，双击要修改许可证类型的系统的名称。
. 在*概述*选项卡上，单击*功能*面板。
. 检查*充电方式*旁边的铅笔图标。如果您的系统的充电方式是 `Node Based`，可以将其转换为按容量充电。
+

TIP: 如果您的Cloud Volumes ONTAP系统已按容量收费，或者任何要求未满足，则该图标将被禁用。

. 在*将基于节点的许可证转换为基于容量的许可证*屏幕上，验证系统名称和源许可证详细信息。
. 选择转换现有许可证的目标包：
+
** 必需品。默认值为 `Essentials`。
** 专业的


. 如果您拥有 BYOL 许可证，则可以在转换完成后选中复选框以从控制台中删除基于节点的许可证。如果转换仍在进行中，选中此复选框将不会从控制台中删除许可证。此选项不适用于市场订阅。
. 选中复选框以确认您了解更改的含义，然后单击“*继续*”。


.完成后
查看新的许可证序列号，并在 NetApp Console 的*管理 > Licenses and subscriptions*菜单中验证更改。



[[conversion-in-a-private-mode-deployment]]
== 专用模式部署中的转换

如果您有专用模式部署，则可以使用 NetApp Console 中的许可证转换工具将基于节点的许可证转换为基于容量的许可证。所有云提供商（AWS、Azure 和 Google Cloud）均支持此转换。

由于私有模式不支持市场订阅，因此您需要从 NetApp 购买 Essentials（自带许可证 (BYOL)）套餐。这样，您无需市场订阅即可在 BYOL 模型中保留基于容量的许可的优势。


NOTE: 私有模式不支持从基于节点的许可证转换为 Essentials 以外的任何基于容量的许可证。

.关于此任务
* 转换后，基于节点的许可证的全部容量将在 Essentials 包下进行跟踪，并继续通过您的 BYOL 协议向您收费。
* 使用许可证转换工具时，将就地执行从基于节点到基于容量的许可模式的转换，从而无需进行任何数据迁移或调配其他云资源。
* 这是一项无中断操作：
+
** 不会发生服务中断或应用程序停机。
** Cloud Volumes ONTAP系统中的帐户和应用程序数据保持不变。
** 转换后，底层云资源不受影响。
** 您的数据将继续保留在与基于节点的许可相同的位置。这种方法可确保数据放置不会中断，并在整个过渡期间维护数据主权原则。


* 许可证转换工具支持所有部署类型，例如单可用区 (AZ) 和多 AZ 中的单节点和高可用性 (HA) 配置。
* 转换后，Cloud Volumes ONTAP 系统将更新新的序列号。


.开始之前
* 由于私有模式 Cloud Volumes ONTAP 部署不支持市场订阅，因此您必须从 NetApp 获取基于容量的 Essentials 许可证。
* 基于容量的许可证应具有与转换的基于节点的许可证类似的容量。
* 基于容量的 Essentials 包应与基于节点的 BYOL 许可证类型相对应。例如，具有辅助卷 (HA) 的专用模式部署应具有相应的 Essentials Secondary HA 许可证或具有最佳匹配的许可证，例如 Essentials Primary、Essentials Primary HA。


.步骤
. 从左侧导航菜单中，选择“存储”>“管理”。
. 在“*系统*”页面上，双击要修改许可证类型的系统的名称。
. 在*概述*选项卡上，单击*功能*面板。
. 检查*Charging method*旁边的铅笔图标。如果系统的收费方式为 `Node Based`，您可以将其转换为基于容量的许可证。
+

TIP: 如果您的Cloud Volumes ONTAP系统已按容量收费，或者任何要求未满足，则该图标将被禁用。

. 在*将基于节点的许可证转换为基于容量的许可证*屏幕上，验证系统名称和源许可证详细信息。
. 选择 Essentials 作为转换现有许可证的目标包：
. 您可以选中该复选框，以便在转换完成后从 Console 中删除基于节点的许可证。如果转换仍在进行中，选中此复选框不会从 Console 中删除许可证。
. 选中复选框以确认您了解更改的含义，然后单击“*继续*”。


.完成后
查看新的许可证序列号，并在 NetApp Console 的*管理 > Licenses and subscriptions*菜单中验证更改。



[[pricing-in-different-hyperscalars]]
== 不同超标量中的定价

有关定价的详细信息，请访问 https://bluexp.netapp.com/pricing/["NetApp Console网站"^]。

有关特定超标量中的私人优惠的信息，请写信至：

* AWS - awspo@netapp.com
* Azure - azurepo@netapp.com
* Google Cloud - gcppo@netapp.com


.相关链接
* link:concept-licensing.html["Cloud Volumes ONTAP许可"]
* link:task-manage-capacity-licenses.html["管理Cloud Volumes ONTAP基于容量的许可"]
* link:task-manage-node-licenses.html["管理基于节点的许可"]

