= Cloud Volumes ONTAP 与 Microsoft OneLake 的集成
:allow-uri-read: 




[[cloud-volumes-ontap-integration-with-microsoft-onelake]]
=== Cloud Volumes ONTAP 与 Microsoft OneLake 的集成

Cloud Volumes ONTAP 现在支持与  https://learn.microsoft.com/en-us/fabric/onelake/onelake-overview["Microsoft OneLake"^] 集成（公开预览版）。您可以使用  https://learn.microsoft.com/en-us/fabric/onelake/onelake-overview["Microsoft OneLake"^] 将 Cloud Volumes ONTAP 与  https://community.fabric.microsoft.com/["Microsoft Fabric"^] 集成，从而使现有的 Cloud Volumes ONTAP NAS 数据可用于 Microsoft 分析和 AI 服务，例如 Power BI、Azure AI Search、OpenAI 和 Microsoft Copilot。此集成不需要进行数据移动或复制。该集成使用  https://docs.netapp.com/us-en/ontap/s3-multiprotocol/index.html["ONTAP S3 多协议"^] 访问将 Cloud Volumes ONTAP 连接到现有的 Microsoft Fabric lakehouse。

.相关文章和资源：
* https://www.netapp.com/blog/optimize-ai-analytics-microsoft-onelake/?utm_content=nativelink&utm_medium=internal&utm_source=linkedin&utm_campaign=b2d-port-all-na-ww-digi-blog-1747859361262&es_id=956c739202["NetApp blog：使用 Microsoft OneLake 和 NetApp Cloud Volumes ONTAP 优化人工智能和分析"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-azure-onelake.html["将 Cloud Volumes ONTAP 系统与 Microsoft OneLake 集成以实现 AI 和分析"^]
* https://www.netapp.com/media/160786-na-1263-netapp-cloud-volumes-ontap-azure-onelake.pdf["Cloud Volumes ONTAP 与 Microsoft OneLake 集成 - 技术简介"^]




[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== 修复、关闭和重新激活 Microsoft Azure 中 Cloud Volumes ONTAP 的配置

NetApp Console 中精心设计的仪表板现在允许您修复 Cloud Volumes ONTAP 系统的配置建议。

您还可以从良好架构分析中忽略一个或多个配置。这样，您可以忽略不适用于您的环境的特定配置。

如果稍后要包含已取消的配置，可以在架构良好的控制面板中重新激活该配置。这会将配置还原到分析中，并允许您获取其建议和修复。

* link:https://docs.netapp.com/us-en/console-well-architected/cvo/improve-configurations-cvo.html["修复、关闭和重新激活 Microsoft Azure 中 Cloud Volumes ONTAP 的配置"^]

