= Cloud Volumes ONTAP 9.19.1 RC
:allow-uri-read: 




[[cloud-volumes-ontap-9-19-1-rc]]
=== Cloud Volumes ONTAP 9.19.1 RC

您现在可以使用 NetApp Console 在 Google Cloud 中部署和管理 Cloud Volumes ONTAP 9.19.1 的 Release Candidate (RC) 版本。此版本不可用于在 Amazon Web Service (AWS) 和 Microsoft Azure (Azure) 中进行部署和升级。

link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/["了解有关此版本Cloud Volumes ONTAP的更多信息"^] 。



[[support-for-next-generation-google-cloud-vms-in-cloud-volumes-ontap-ha]]
=== 支持 Cloud Volumes ONTAP HA 中的下一代 Google Cloud VM

借助 9.19.1，NetApp 将 Cloud Volumes ONTAP 高可用性 (HA) 部署从 N2 虚拟机迁移到下一代 Google Cloud C3 系列虚拟机，以获得更快、更具可扩展性的体验。


NOTE: 此支持仅适用于单可用区 (AZ) HA 部署。

现在，您可以在 Google Cloud 中部署 Cloud Volumes ONTAP 9.19.1 及更高版本时利用 C3 系列虚拟机。这些机器具有更高的性能和更大的容量限制。它们使用 Google Virtual NIC (gVNIC) 和 Hyperdisk Balanced 磁盘，在密集型工作负载上实现动态性能。

如果您的 Cloud Volumes ONTAP 系统运行 9.19.1 或更高版本，则用于在单个 AZ 中轻松部署的预配置包将自动使用 C3 VM，同时使您能够根据工作负载需求自定义 IOPS 和吞吐量参数。同样，在创建聚合时，您可以添加 Zonal Hyperdisk Balanced 磁盘，以在 Google Cloud 中实现更好的性能和可扩展性。您还可以选择 C3 系列机器的 LSSD 变体，以获得默认 Flash Cache 支持。

请注意以下几点：

* 在 Cloud Volumes ONTAP 部署中，您无法将 C3 虚拟机更改为 N2 系列虚拟机，反之亦然。但是，您可以在 C3 系列中的不同变体之间切换实例类型。
+

NOTE: 根据连接的数据磁盘数量，更改 C3 系列中的实例类型可能需要更长时间。请提前规划您的配置，以避免对性能造成影响。

* 更改实例类型时，如果选择 c3-standard-44 或 c3-standard-88 及其本地 SSD (LSSD) 变体作为目标 VM，则会自动应用 Google 网络服务 egress network tier _Tier-1_。如果切换回任何其他 C3 变体，则出口网络层将设置为 _Standard_。
+

NOTE: 将出口网络层更改为 _Tier-1_ 会产生额外费用。请相应地规划部署和升级。

* 如果选择 C3 的 LSSD 变体，默认情况下会启用 Flash Cache。即使目标变体支持 Flash Cache，您也无法在 Cloud Volumes ONTAP 部署中的 C3 LSSD 变体之间切换。
* 在 C3 虚拟机上，您可以向新的和现有的聚合添加卷。
* 将 N2 VM 类型的 Cloud Volumes ONTAP 系统复制到 C3 VM 类型时，磁盘类型默认设置为 Hyperdisk Balanced。
* 通过 NetApp Console 或使用 `PUT /gcp/ha/aggregates/{workingEnvironmentId}/{aggregateName}` API 添加聚合时，可以更改 IOPS 和吞吐量设置。


https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Google Cloud 中 Cloud Volumes ONTAP 支持的配置"^]

https://docs.cloud.google.com/compute/docs/general-purpose-machines#c3_series["Google 文档：C3 机器系列"^]



[[simplified-cloud-volumes-ontap-deployment-in-google-cloud]]
=== 简化 Google Cloud 中的 Cloud Volumes ONTAP 部署

现在，您可以使用*快速创建*向导在 Google Cloud 中为单节点和高可用性 (HA) 配置部署 Cloud Volumes ONTAP。这种简化的流程减少了步骤，在单个页面上自动设置默认值，并最大限度地减少导航操作，从而实现更快、更轻松的部署。

.相关链接
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-gcp.html["使用 Quick create 在 Google Cloud 中部署 Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-gcp.html["使用 Google Cloud 中的高级选项部署 Cloud Volumes ONTAP"^]




[[introducing-access-roles-for-cloud-volumes-ontap]]
=== Cloud Volumes ONTAP 访问角色简介

NetApp 为 Cloud Volumes ONTAP 引入了身份和访问管理 (IAM) 角色，实现了基于角色的访问控制 (RBAC)，以提升安全性并简化合规管理。用户可以继续使用其现有凭据登录 NetApp Console，以执行 Cloud Volumes ONTAP 操作。但是，身份验证现在通过身份联合进行路由，使 Console 管理员能够对这些功能进行更精细的控制。每个用户必须具有以下角色之一，才能对 Cloud Volumes ONTAP 执行任何操作。如果没有角色，用户将无法查看或访问 Cloud Volumes ONTAP 实例。

* *Cloud Volumes ONTAP viewer*：授予对 Cloud Volumes ONTAP 屏幕和选项卡的只读访问权限。此角色中禁用了某些屏幕和操作按钮。
* *Cloud Volumes ONTAP operator*：启用日常管理任务，例如添加卷、管理存储和配置复制。
* *Cloud Volumes ONTAP admin*：提供对所有 Cloud Volumes ONTAP 操作的完全访问权限。


Console 管理员从*管理 > 身份*为 Cloud Volumes ONTAP 用户分配角色。角色权限基于用户的组织，并应用于该组织中的所有 Cloud Volumes ONTAP 系统。

Cloud Volumes ONTAP 使用每个用户权限的本地缓存强制执行 RBAC，该缓存每小时自动刷新一次。当为用户分配新角色或更改其现有角色时，该更改可能需要最多一小时才能生效，此后，角色允许的所有工作流将被启用。


NOTE: 首次部署 Console 代理或将现有 Console 代理升级到 Console 4.9.0 或更高版本时，一次性种子设定过程会自动将 Cloud Volumes ONTAP 角色分配给组织中的所有现有用户。此过程最多可能需要 30 分钟才能完成。完成后，Console 将为现有用户分配适当的角色。

Cloud Volumes ONTAP 角色适用于 Amazon Web Service (AWS)、Microsoft Azure (Azure) 和 Google Cloud 环境。

.相关链接
* https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["NetApp Console 访问角色"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-iam-cvo-roles.html["Cloud Volumes ONTAP 访问角色（位于 NetApp Console 中）"^]

